# Generated by Django 2.2.12 on 2020-06-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('serving', 'serving'), ('count', 'count'), ('package', 'package')], default='serving', max_length=16)),
                ('exp_date', models.DateField()),
                ('category', models.CharField(choices=[('meat', 'meat'), ('vegetable', 'vegetable'), ('fruit', 'fruit'), ('eggs', 'eggs'), ('carb', 'carb'), ('dairy', 'dairy'), ('misc', 'misc')], default='misc', max_length=16)),
            ],
        ),
    ]
