# Generated by Django 2.2.12 on 2020-06-03 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('meat', 'meat'), ('vegetable', 'vegetable'), ('fruit', 'fruit'), ('eggs', 'eggs'), ('carbs', 'carbs'), ('dairy', 'dairy'), ('misc', 'misc')], default='misc', max_length=16),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('step', models.CharField(max_length=2048)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction', to='food_items.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingredient', to='food_items.Recipe')),
            ],
        ),
    ]
