version: '3.1'

services:
  db:
    image: "postgres:alpine"
    environment: 
      POSTGRES_PASSWORD: waste_not
      POSTGRES_USER: waste_not
      POSTGRES_DB: waste_not
      
    volumes:
      - .db:/var/lib/postgresql/data

  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env.production
    depends_on:
      - db
      - frontend
